builds:
  - binary: supper
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: >
      -s -w
      -X github.com/tympanix/supper/app/cli.appVersion={{.Version}}
      -X github.com/tympanix/supper/app/cli.appCommit={{.Commit}}
      -X github.com/tympanix/supper/app/cli.appDate={{.Date}}

      -X github.com/tympanix/supper/media/provider.tmdbToken={{.Env.TMDB_TOKEN}}
      -X github.com/tympanix/supper/media/provider.thetvdbToken={{.Env.THETVDB_TOKEN}}
nfpm:
  vendor: github.com/tympanix
  maintainer: tympanix <tympanix@gmail.com>
  description: A blazingly fast multimedia manager
  license: GNU-v3.0
  formats:
    - deb
  files:
    ./etc/supper.service: /lib/systemd/system/supper.service
  config_files:
    ./etc/supper.yaml: /etc/supper/supper.yaml
  scripts:
    preinstall: ./etc/preinstall.sh
    postinstall: ./etc/postinstall.sh
